### ISSUE TITLE
Nim 0.20.0 released and not compatable with scgi

### ISSUE THREAD

**Issue by kerneltravel** [nim-lang/graveyard#11]
currently  used version:
nim version: 0.20.0
scgi-0.1.0

after 
```
nimble install  scgi 
```
,and
```
nim c forum.nim
```
got ERROR:
/home/user/.nimble/pkgs/scgi-0.1.0/scgi.nim(35, 8) Error: cannot open file: sockets
/home/user/.nimble/pkgs/scgi-0.1.0/scgi.nim(95, 11) Error: undeclared identifier: 'Dispatcher',and someother errors.
it seems the latest nim is not compatable with scgi.

**Comment by Araq** [comment]
Well it's a graveyard, PRs are welcome but we will not fix it on our own, sorry.
