### ISSUE TITLE
queues removed from stdlib but isnt' in graveyard

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/graveyard#8]
/cc @narimiran refs https://github.com/nim-lang/Nim/pull/10347

**Comment by dom96** [comment]
queues was deprecated AFAIK, you're supposed to use dequeues, no?

**Comment by timotheecour** [comment]
> 
From IRC (bridge bot) @FromIRC 05:12
<kobi7> now I get cannot open file queues, from yaml package. I saw it was removed in favour of deques :⁠-)

**Comment by narimiran** [comment]
Queues were deprecated a long time ago, and shouldn't be used (that means they shouldn't be moved to graveyard).

It is time to update the packages depending on deprecated libraries.

**Comment by dom96** [comment]
Maybe next time ask in IRC instead of creating an issue so quickly.

**Comment by timotheecour** [comment]
fine but maybe  'Packages from Nim stdlib that are no longer in use are kept here in case external packages still depend on it.' mentioned in README shd be updated a bit to reflect the scope of what gets moved to graveyard
